# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.ImageField(default='gallery/media/images', upload_to='images'),
        ),
    ]
