# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_image_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='email',
        ),
    ]
