# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_remove_image_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['posted_by']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='posted_by',
        ),
    ]
